name       : gnome-shell-extension-impatience
version    : 0.4.5
release    : 6
source     :
    - git|https://github.com/timbertson/gnome-shell-impatience.git : 33ac96b8b6593ba98408c460e7d2ee1803dc41e5
license    : GPL-3.0-or-later
component  : desktop.gnome
summary    : Speed up GNOME Shell animations with the Impatience extension.
description: |
    Speed up GNOME Shell animations with the Impatience extension.
rundeps    :
    - gnome-shell
    - gnome-shell-extensions
setup      : |
    %patch -p1 < $pkgfiles/0001-Resolve-schema-detection-and-modify-default-speed-fa.patch
install    : |
    install -dm00755 $installdir/usr/share/glib-2.0/schemas/
    export gseDir=$installdir/usr/share/gnome-shell/extensions/impatience@gfxmonk.net/
    install -dm00755 ${gseDir}
    cd impatience
    install -Dm00644 schemas/org.*xml $installdir/usr/share/glib-2.0/schemas/
    rm -r schemas
    cp -R * ${gseDir}
    chmod 00644 ${gseDir}/*
