name       : gnome-shell-extension-impatience
version    : 0.4.8
release    : 12
source     :
    - git|https://github.com/timbertson/gnome-shell-impatience.git : 0f961b860040ba0f7bbb51ebbaece7db29787313
license    : GPL-3.0-or-later
component  : desktop.gnome
summary    : Speed up GNOME Shell animations with the Impatience extension.
description: |
    Speed up GNOME Shell animations with the Impatience extension.
rundeps    :
    - gnome-shell
    - gnome-shell-extensions
#setup      : |
#    %patch -p1 < $pkgfiles/0001-Resolve-schema-detection-and-modify-default-speed-fa.patch
install    : |
    install -dm00755 $installdir/usr/share/glib-2.0/schemas/
    export gseDir=$installdir/usr/share/gnome-shell/extensions/impatience@gfxmonk.net/
    install -dm00755 ${gseDir}
    cd impatience
    install -Dm00644 schemas/org.*xml $installdir/usr/share/glib-2.0/schemas/
    rm -r schemas
    cp -R * ${gseDir}
    chmod 00644 ${gseDir}/*
